# Site settings
title: Watermelon Man
email: brian.lxchen@gmail.com
url: https://icheft.github.io/climas
description: "嗨！你正在看西瓜人配色的 CLIMAS 網站！"
meta_author: CLIMAS
# keywords: "your keywords, separated by commas"
# skills: "Web Developer - Graphic Artist - User Experience Designer"

# Google webmaster tools
# google_verify:
google_ID: UA-162829284-2

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F35588 #80B3FF
  primary-rgb: "243,85,136" #"128,179,255"
  secondary: 71A95A #FD6E8A 2c3e50
  secondary-dark: 007944 #A2122F  233140

# Footer settings
footer:
  copyright: Brian L. Chen
  # location: Location
  # social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#  - title: stack-overflow
# url: http://stackoverflow.com/questions/tagged/jekyll
social:
  - title: facebook
    url: https://www.facebook.com/brian.lxchen
  - title: github
    url: http://github.com/icheft
  - title: instagram
    url: https://instagram.com/brian_lxchen
  - title: envelope
    url: mailto:brian.lxchen@gmail.com
  - title: linkedin
    url: https://www.linkedin.com/in/brianlhchen/

# Postal address (add as many lines as necessary)
address:
  - line: NTU
  - line: Taiwan

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
